version: '3.4'

services:
  events:
    image: spozoga/events.pozoga.eu
    environment:
      TZ: 'Europe/Warsaw'
    restart: always
    environment:
      - "DB_HOST=db"
      - "DB_PORT=3306"
      - "DB_NAME=YOUR_DATABSE_NAME"
      - "DB_USER=YOUR_DATABSE_USER_NAME"
      - "DB_PASS=YOUR_DATABSE_USER_PASSWRD"
      - "WP_USER=YOUR_WORDPRESS_USER_NAME"
      - "WP_PASS=YOUR_WORDPRESS_USER_PASSWORD"
      - "WP_EMAIL=YOUR_WORDPRESS_USER_EMAIL"
      - "WP_HOST=YOUR_WORDPRESS_APP_HOST"
      - "WP_TITLE=YOUR_WORDPRESS_USER_TITLE"
    volumes:
      - "/dockerdata/sebastianpozoga/events.pozoga.eu/uploads:/var/www/html/wp-content/uploads"
    ports:
      - 80:80
      - 8080:8080
  db:
    image: mariadb
    restart: always
    environment:
      - "MYSQL_DATABASE=YOUR_DATABSE_NAME"
      - "MYSQL_USER=YOUR_DATABSE_USER_NAME"
      - "MYSQL_PASSWORD=YOUR_DATABSE_USER_PASSWRD"
      - "MYSQL_ROOT_PASSWORD=YOUR_DATABSE_ROOT_PASSWRD"
    volumes:
      - "/dockerdata/sebastianpozoga/events.pozoga.eu/mysql:/var/lib/mysql"
